# Generated by Django 2.2a1 on 2019-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=9000)),
            ],
        ),
    ]
