# Generated by Django 2.2a1 on 2019-02-22 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 2, 22, 18, 25, 7, 85869, tzinfo=utc))),
                ('comment', models.CharField(max_length=9000)),
            ],
        ),
    ]
