# Generated by Django 2.1.7 on 2019-02-24 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 15, 53, 1, 439425, tzinfo=utc)),
        ),
    ]
