# Generated by Django 2.1.7 on 2019-02-24 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_auto_20190224_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 18, 46, 7, 369783, tzinfo=utc)),
        ),
    ]
