# Generated by Django 2.1.7 on 2019-02-26 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_auto_20190226_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 21, 19, 44, 19442, tzinfo=utc)),
        ),
    ]
