# Generated by Django 2.1.7 on 2019-02-26 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_auto_20190226_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('WH', 'Wheat'), ('RI', 'Rice'), ('CO', 'Cotton'), ('SU', 'Sugarcane'), ('GR', 'Groundnut'), ('PO', 'Potato'), ('MU', 'Mustard'), ('MI', 'Millet'), ('PU', 'Pulse'), ('COF', 'Coffee'), ('TE', 'Tea'), ('JU', 'Jute'), ('MA', 'Maize'), ('TO', 'Tomato')], default='WH', max_length=3)),
                ('insect_name', models.TextField(max_length=300)),
                ('img1', models.ImageField(upload_to='photos')),
                ('img2', models.ImageField(upload_to='photos')),
                ('img3', models.ImageField(upload_to='photos')),
                ('sympt', models.TextField(max_length=9000)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 21, 55, 20, 491471, tzinfo=utc)),
        ),
    ]
