# Generated by Django 2.1.7 on 2019-02-27 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_auto_20190226_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 5, 7, 5, 217855, tzinfo=utc)),
        ),
    ]
