# Generated by Django 2.1.7 on 2019-02-27 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0013_auto_20190227_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 5, 22, 15, 798538, tzinfo=utc)),
        ),
    ]
