# Generated by Django 2.1.7 on 2019-02-27 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0014_auto_20190227_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 5, 44, 11, 314060, tzinfo=utc)),
        ),
    ]
