# Generated by Django 2.1.7 on 2019-03-01 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_auto_20190227_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 11, 1, 45, 105747, tzinfo=utc)),
        ),
    ]
