# Generated by Django 2.1.7 on 2019-03-02 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0017_auto_20190301_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 9, 18, 32, 674929, tzinfo=utc)),
        ),
    ]
