# Generated by Django 2.1.7 on 2019-03-02 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0018_auto_20190302_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 9, 22, 56, 516999, tzinfo=utc)),
        ),
    ]
