# Generated by Django 2.1.7 on 2019-04-04 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0025_auto_20190302_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 11, 32, 9, 411414, tzinfo=utc)),
        ),
    ]
