# Generated by Django 2.1.7 on 2019-02-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('WH', 'Wheat'), ('RI', 'Rice'), ('CO', 'Cotton'), ('SU', 'Sugarcane'), ('GR', 'Groundnut'), ('PO', 'Potato'), ('MU', 'Mustard'), ('MI', 'Millet'), ('PU', 'Pulse'), ('COF', 'Coffee'), ('TE', 'Tea'), ('JU', 'Jute'), ('MA', 'Maize'), ('TO', 'Tomato')], default='WH', max_length=3)),
                ('disease_name', models.TextField(max_length=300)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('symptom', models.TextField(max_length=9000)),
                ('chem_sol', models.TextField(max_length=9000)),
                ('cult_sol', models.TextField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
