# Generated by Django 2.1.7 on 2019-02-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('WH', 'Wheat'), ('RI', 'Rice'), ('CO', 'Cotton'), ('SU', 'Sugarcane'), ('GR', 'Groundnut'), ('PO', 'Potato'), ('MU', 'Mustard'), ('MI', 'Millet'), ('PU', 'Pulse'), ('COF', 'Coffee'), ('TE', 'Tea'), ('JU', 'Jute'), ('MA', 'Maize'), ('TO', 'Tomato')], default='WH', max_length=3)),
                ('insect_name', models.TextField(max_length=300)),
                ('img1', models.ImageField(upload_to='photos')),
                ('img2', models.ImageField(upload_to='photos')),
                ('img3', models.ImageField(upload_to='photos')),
                ('sympt', models.TextField(max_length=9000)),
                ('sol', models.TextField(max_length=9000, null=True)),
            ],
        ),
    ]
