# Generated by Django 2.1.7 on 2019-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0002_insectmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insectmodel',
            name='sol',
        ),
        migrations.AddField(
            model_name='insectmodel',
            name='biological_control',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AddField(
            model_name='insectmodel',
            name='chem_control',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AddField(
            model_name='insectmodel',
            name='preventive_measures',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AddField(
            model_name='insectmodel',
            name='trigger',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='insectmodel',
            name='sympt',
            field=models.TextField(blank=True, max_length=9000),
        ),
    ]
