# Generated by Django 2.1.7 on 2019-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0003_auto_20190227_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insectmodel',
            name='crop_name',
            field=models.CharField(choices=[('WH', 'Wheat'), ('RI', 'Rice'), ('CO', 'Cotton'), ('SU', 'Sugarcane'), ('GR', 'Groundnut'), ('PO', 'Potato'), ('MU', 'Mustard'), ('MI', 'Millet'), ('PU', 'Pulse'), ('COF', 'Coffee'), ('TE', 'Tea'), ('JU', 'Jute'), ('MA', 'Mango'), ('TO', 'Tomato')], default='WH', max_length=3),
        ),
        migrations.AlterField(
            model_name='insectmodel',
            name='img1',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='insectmodel',
            name='img2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='insectmodel',
            name='img3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
