# Generated by Django 2.1.7 on 2019-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0004_auto_20190301_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomato_Bacterial_spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptm', models.CharField(max_length=200)),
                ('mechanical', models.CharField(max_length=200)),
                ('chemical', models.CharField(max_length=200)),
                ('physical', models.CharField(max_length=200)),
                ('pesticide', models.CharField(max_length=10)),
            ],
        ),
    ]
