# Generated by Django 2.1.7 on 2019-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0005_tomato_bacterial_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato_bacterial_spot',
            name='chemical',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='tomato_bacterial_spot',
            name='mechanical',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='tomato_bacterial_spot',
            name='pesticide',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='tomato_bacterial_spot',
            name='physical',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='tomato_bacterial_spot',
            name='symptm',
            field=models.CharField(max_length=9000),
        ),
    ]
