# Generated by Django 2.1.7 on 2019-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0007_tomato_tomato_yellowleaf_curl_virus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potato_Early_blight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptm', models.CharField(max_length=9000)),
                ('mechanical', models.CharField(max_length=9000)),
                ('chemical', models.CharField(max_length=9000)),
                ('physical', models.CharField(max_length=9000)),
                ('pesticide', models.CharField(max_length=9000)),
            ],
        ),
    ]
