# Generated by Django 2.1.7 on 2019-03-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0008_potato_early_blight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='image1',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='image2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='image3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
