# Generated by Django 2.1.7 on 2019-04-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0009_auto_20190302_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
